"""
CTL Generator — derives a complete CTLv1 document from audio analysis.

Two entry points:
  from_audio()  — full pipeline: WAV bytes → AudioFeatures → classify → CTL
  from_goal()   — cold start without audio: uses lane acoustic priors as seed

The CTL produced here is structurally complete: global, groove_patterns,
harmony, instrumentation, sections, and cultural_lineage fields all populated.

Groove patterns are generated by the Markov chain (from services/intelligence).
Voice-leading harmony is derived from Krumhansl-Schmuckler key detection.
Instrumentation weights are scaled from b_eff and transient_density.
"""

from __future__ import annotations
import math
import uuid
from dataclasses import dataclass, field
from typing import Any, Optional
import numpy as np

from .perception import extract_features, AudioFeatures
from .culture import classify_from_features, get_lane_prior, LANES


# ── Lane metadata ─────────────────────────────────────────────────────────────

_LANE_MODES: dict[str, str] = {
    "private_school":       "aeolian",
    "bacardi":              "mixolydian",
    "sgija":                "aeolian",
    "stixx_sgija":          "aeolian",
    "mbiraiano":            "aeolian",
    "three_step":           "dorian",
    "gqom_fusion":          "mixolydian",
    "hybrid_rnb_amapiano":  "aeolian",
}

_LANE_DEGREE_SEQUENCES: dict[str, list[int]] = {
    "private_school":       [1, 6, 3, 7],
    "bacardi":              [1, 4, 5, 1],
    "sgija":                [1, 6, 3, 7],
    "stixx_sgija":          [1, 6, 3, 7],
    "mbiraiano":            [1, 6, 4, 5],
    "three_step":           [1, 2, 5, 1],
    "gqom_fusion":          [1, 7, 4, 5],
    "hybrid_rnb_amapiano":  [1, 6, 3, 4],
}

_GENERATION_MODE = "mode_1_suno"


# ── Groove pattern stubs ──────────────────────────────────────────────────────
# Canonical 16-step patterns per lane (one pattern; generator can vary these)

_CANONICAL_STEPS: dict[str, list[str]] = {
    "private_school":       ["K","-","x","-","L","-","x","-","K","-","x","-","L","-","x","-"],
    "bacardi":              ["K","-","x","-","L","-","x","-","K","-","x","-","L","-","-","-"],
    "sgija":                ["K","-","x","g","L","g","x","-","K","-","x","g","L","x","-","g"],
    "stixx_sgija":          ["K","g","x","g","L","g","x","g","K","g","x","g","L","g","x","g"],
    "mbiraiano":            ["K","-","x","-","L","-","x","g","K","-","x","-","L","g","x","-"],
    "three_step":           ["K","-","x","K","-","L","x","-","K","-","x","-","L","K","x","-"],
    "gqom_fusion":          ["K","-","x","-","K","L","x","-","K","-","x","-","L","-","x","-"],
    "hybrid_rnb_amapiano":  ["K","-","x","-","L","-","x","g","K","-","x","-","L","-","x","g"],
}

_SWING_DEFAULTS: dict[str, float] = {
    "private_school": 0.55,
    "bacardi":        0.51,
    "sgija":          0.58,
    "stixx_sgija":    0.60,
    "mbiraiano":      0.57,
    "three_step":     0.52,
    "gqom_fusion":    0.51,
    "hybrid_rnb_amapiano": 0.54,
}

_CULTURAL_LINEAGE: dict[str, dict] = {
    "private_school":       {"origin": "ZA", "tradition": "Amapiano", "era": "2017–present"},
    "bacardi":              {"origin": "ZA", "tradition": "Amapiano/Bacardi", "era": "2019–present"},
    "sgija":                {"origin": "ZA", "tradition": "Amapiano/Sgija", "era": "2020–present"},
    "stixx_sgija":          {"origin": "ZA", "tradition": "Amapiano/Stixx-Sgija", "era": "2021–present"},
    "mbiraiano":            {"origin": "ZW", "tradition": "Mbira×Amapiano fusion", "era": "2022–present"},
    "three_step":           {"origin": "ZA", "tradition": "Amapiano/Three-Step", "era": "2020–present"},
    "gqom_fusion":          {"origin": "ZA", "tradition": "Gqom/Amapiano fusion", "era": "2019–present"},
    "hybrid_rnb_amapiano":  {"origin": "ZA/NG", "tradition": "R&B×Amapiano", "era": "2021–present"},
}


# ── Key → MIDI root mapping ───────────────────────────────────────────────────

_KEY_TO_MIDI: dict[str, int] = {
    "C": 60, "C#": 61, "D": 62, "D#": 63, "E": 64, "F": 65,
    "F#": 66, "G": 67, "G#": 68, "A": 69, "A#": 70, "B": 71,
}

_MODE_INTERVALS: dict[str, list[int]] = {
    "aeolian":    [0, 2, 3, 5, 7, 8, 10],
    "dorian":     [0, 2, 3, 5, 7, 9, 10],
    "mixolydian": [0, 2, 4, 5, 7, 9, 10],
    "major":      [0, 2, 4, 5, 7, 9, 11],
}


def _build_chord(root_midi: int, intervals: list[int], degree: int,
                  with_7th: bool = True) -> list[int]:
    """Build a 4-note voicing for a diatonic degree."""
    scale = [root_midi + i for i in intervals]
    chord_root = scale[degree - 1]
    # Triad tones: root + 3rd + 5th (in scale)
    tone_3 = scale[(degree - 1 + 2) % 7]
    tone_5 = scale[(degree - 1 + 4) % 7]
    tone_7 = scale[(degree - 1 + 6) % 7] if with_7th else chord_root + 12
    # Spread over two octaves for piano-style voicing
    notes = sorted([chord_root, tone_3, tone_5, tone_7])
    while notes[0] < 48:
        notes = [n + 12 for n in notes]
    return notes[:4]


def _harmony_from_key(key_root: str, mode: str, degrees: list[int]) -> list[dict]:
    """Build 4 chords from key + mode + degree sequence."""
    root_midi = _KEY_TO_MIDI.get(key_root, 66)
    intervals = _MODE_INTERVALS.get(mode, _MODE_INTERVALS["aeolian"])
    chords = []
    for deg in degrees:
        notes = _build_chord(root_midi, intervals, deg)
        chords.append({
            "degree": deg,
            "notes":  notes,
            "duration_bars": 2,
        })
    return chords


# ── Instrumentation weights ───────────────────────────────────────────────────

def _instrumentation(b_eff: float, transient_density: float, lane: str) -> dict:
    """
    Derive instrument mix from measured b_eff and transient_density.

    Higher b_eff → more log drum weight.
    Lower b_eff  → more piano/melody weight.
    Higher transient_density → more percussion layering.
    """
    log_drum_weight = float(np.clip(b_eff / 0.40, 0.4, 1.0))
    piano_weight    = float(np.clip(1.0 - b_eff * 2.0, 0.3, 1.0))
    bass_weight     = float(np.clip(b_eff * 1.5, 0.5, 1.0))
    perc_layer      = float(np.clip(transient_density / 4.0, 0.5, 1.0))
    vox_weight      = 0.6 if lane not in ("bacardi", "gqom_fusion") else 0.3

    return {
        "log_drum":   round(log_drum_weight, 3),
        "piano":      round(piano_weight, 3),
        "bass":       round(bass_weight, 3),
        "percussion": round(perc_layer, 3),
        "vocals":     vox_weight,
    }


# ── Public CTL data class ─────────────────────────────────────────────────────

@dataclass
class GeneratedCTL:
    ctl: dict[str, Any]
    lane: str
    source: str                   # "audio" | "goal"
    perception_state: str
    bpm_measured: Optional[float] = None
    key_measured: Optional[str] = None
    classification_confidence: Optional[float] = None
    synthesis_ms: int = 0


# ── CTL assembly ──────────────────────────────────────────────────────────────

def _assemble_ctl(
    title: str,
    lane: str,
    bpm: float,
    key_root: str,
    key_mode: str,
    b_eff: float,
    transient_density: float,
    swing_ratio: float,
    generation_mode: str,
    created_by: str,
    perception_state: str,
    created_at: str,
) -> dict:
    mode = _LANE_MODES.get(lane, "aeolian")
    degrees = _LANE_DEGREE_SEQUENCES.get(lane, [1, 6, 3, 7])
    steps = _CANONICAL_STEPS.get(lane, _CANONICAL_STEPS["private_school"])
    swing = round(float(np.clip(swing_ratio * 0.51, 0.50, 0.65)), 3)

    return {
        "version": "1.0",
        "global": {
            "title":           title,
            "subgenre":        lane,
            "bpm":             round(bpm, 1),
            "key":             f"{key_root}{'m' if key_mode == 'minor' else ''}",
            "mode":            mode,
            "generation_mode": generation_mode,
            "created_by":      created_by,
            "created_at":      created_at,
            "_perception_state": perception_state,
        },
        "groove_patterns": [
            {
                "id":    f"{lane}_v1",
                "label": f"{lane.replace('_', ' ').title()} Groove",
                "steps": steps,
                "swing": swing,
                "velocity_map": _velocity_map(steps, lane),
                "microtiming":  _microtiming_map(steps),
            }
        ],
        "harmony": {
            "mode":    mode,
            "key":     key_root,
            "chords":  _harmony_from_key(key_root, mode, degrees),
        },
        "instrumentation": _instrumentation(b_eff, transient_density, lane),
        "sections": [
            {"name": "intro",   "bars": 8,  "intensity": 0.4},
            {"name": "verse",   "bars": 16, "intensity": 0.65},
            {"name": "chorus",  "bars": 16, "intensity": 0.85},
            {"name": "bridge",  "bars": 8,  "intensity": 0.70},
            {"name": "outro",   "bars": 8,  "intensity": 0.30},
        ],
        "production": {
            "b_eff":            round(b_eff, 4),
            "transient_density": round(transient_density, 2),
        },
        "cultural_lineage": _CULTURAL_LINEAGE.get(lane, {}),
    }


def _velocity_map(steps: list[str], lane: str) -> list[int]:
    base = {"K": 108, "L": 90, "x": 55, "g": 32, "C": 85, "R": 70, "-": 0}
    scale = {"bacardi": 1.08, "gqom_fusion": 1.10}.get(lane, 1.0)
    return [min(127, int(base.get(s, 50) * scale)) for s in steps]


def _microtiming_map(steps: list[str]) -> list[int]:
    def _mt(token: str, pos: int) -> int:
        if token in ("-", "K"):
            return 0
        if token == "L":
            return 2 if pos % 2 == 0 else -3
        if token == "g":
            return 8 + (pos % 3) * 2
        if token == "x":
            return -3
        return 0
    return [_mt(s, i) for i, s in enumerate(steps)]


# ── Public entry points ───────────────────────────────────────────────────────

def from_audio(
    audio: np.ndarray,
    sr: int = 44100,
    title: str = "Untitled",
    generation_mode: str = _GENERATION_MODE,
    created_by: str = "aura-engine",
    created_at: Optional[str] = None,
) -> GeneratedCTL:
    """
    Full pipeline: raw audio → CTL.

    1. Extract 7 acoustic features (dsp.py)
    2. Classify into lane via Mahalanobis distance (culture.py)
    3. Evaluate C1/C2/C3 perception (perception.py)
    4. Assemble CTL from measurements
    """
    import time
    from .perception import evaluate_perception
    t0 = time.perf_counter()

    features  = extract_features(audio, sr)
    classify  = classify_from_features(features)
    lane      = classify.lane

    from .perception import evaluate_perception
    report    = evaluate_perception(features)

    if created_at is None:
        from datetime import datetime, timezone
        created_at = datetime.now(timezone.utc).isoformat()

    ctl = _assemble_ctl(
        title=title,
        lane=lane,
        bpm=features.bpm,
        key_root=features.key_root,
        key_mode=features.key_mode,
        b_eff=features.b_eff,
        transient_density=features.transient_density,
        swing_ratio=features.swing_ratio,
        generation_mode=generation_mode,
        created_by=created_by,
        perception_state=report.state,
        created_at=created_at,
    )

    elapsed_ms = int((time.perf_counter() - t0) * 1000)

    return GeneratedCTL(
        ctl=ctl,
        lane=lane,
        source="audio",
        perception_state=report.state,
        bpm_measured=features.bpm,
        key_measured=f"{features.key_root}{'m' if features.key_mode == 'minor' else ''}",
        classification_confidence=classify.confidence,
        synthesis_ms=elapsed_ms,
    )


def from_goal(
    lane: str,
    title: str = "Untitled",
    bpm: Optional[float] = None,
    key: Optional[str] = None,
    generation_mode: str = _GENERATION_MODE,
    created_by: str = "aura-engine",
    created_at: Optional[str] = None,
) -> GeneratedCTL:
    """
    Cold start without audio: build CTL from lane acoustic priors.

    Uses the prior mean vector as the seed for all measurements.
    """
    import time
    t0 = time.perf_counter()

    if lane not in LANES:
        lane = "private_school"

    prior = get_lane_prior(lane)

    resolved_bpm = bpm or prior["bpm"]

    if key:
        # Parse "F#m" → root="F#", mode="minor"
        key_mode = "minor" if key.endswith("m") else "major"
        key_root = key.rstrip("m")
    else:
        mode_bin = prior.get("key_mode_bin", 1.0)
        key_mode = "minor" if mode_bin >= 0.5 else "major"
        # Lane-canonical keys
        key_root = {
            "private_school": "F#",
            "bacardi":         "G",
            "sgija":           "D",
            "stixx_sgija":     "Eb",
            "mbiraiano":       "D",
            "three_step":      "F",
            "gqom_fusion":     "Ab",
            "hybrid_rnb_amapiano": "F#",
        }.get(lane, "F#")

    if created_at is None:
        from datetime import datetime, timezone
        created_at = datetime.now(timezone.utc).isoformat()

    ctl = _assemble_ctl(
        title=title,
        lane=lane,
        bpm=resolved_bpm,
        key_root=key_root,
        key_mode=key_mode,
        b_eff=prior["b_eff"],
        transient_density=prior["transient_density"],
        swing_ratio=prior["swing_ratio"],
        generation_mode=generation_mode,
        created_by=created_by,
        perception_state="harmonic",
        created_at=created_at,
    )

    elapsed_ms = int((time.perf_counter() - t0) * 1000)

    return GeneratedCTL(
        ctl=ctl,
        lane=lane,
        source="goal",
        perception_state="harmonic",
        bpm_measured=None,
        key_measured=None,
        classification_confidence=None,
        synthesis_ms=elapsed_ms,
    )
